import '@repo/shared/src/styles.css';
import type { Metadata } from 'next';

import { gowunBatang, notoSerifKr, pretendard } from '@/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body
        className={`font-sans leading-relaxed tracking-tight text-slate-700 ${pretendard.variable} ${gowunBatang.variable} ${notoSerifKr.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
